services:
  nlw_setup_database:
    image: postgres
    container_name: nlw_setup_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}    
  
  # app:
  #   build: .
  #   container_name: nlw_setup_app
  #   restart: always
  #   environment:
  #     - DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@nlw_setup_database:5432/${POSTGRES_DB}"
  #     - PORT=${PORT}
  #   ports:
  #     - 3333:3333
  #   volumes:
  #   - .:/usr/app
  #   links:
  #   - nlw_setup_database
  #   depends_on:
  #   - nlw_setup_database
